data_properties = [
    [[{'id': 2509325664, 'name': 'auberge de bondy',
       'address': {'streetAddress': '91 Rue Louis Auguste Blanqui', 'extendedAddress': '', 'locality': 'Bondy',
                   'postalCode': '93140', 'region': 'Seine-Saint-Denis', 'countryName': 'France', 'countryCode': 'fr',
                   'obfuscate': False},
       'landmarks': [{'label': 'City center', 'distance': '7.0 miles'},
                     {'label': 'Eiffel Tower', 'distance': '9.2 miles'}],
       'ratePlan': {'price': {'current': '$18', 'exactCurrent': 18.39, 'old': '$23'}}},
      {'id': 233832, 'name': 'Cyan Hotel Roissy Villepinte Parc Des Expositions',
       'address': {'streetAddress': '53 Avenue des Nations', 'extendedAddress': '', 'locality': 'Villepinte',
                   'postalCode': '95973', 'region': 'Roissy en France', 'countryName': 'France', 'countryCode': 'fr',
                   'obfuscate': False},
       'landmarks': [{'label': 'City center', 'distance': '11 miles'},
                     {'label': 'Eiffel Tower', 'distance': '13 miles'}],
       'ratePlan': {'price': {'current': '$26', 'exactCurrent': 25.92}}},
      {'id': 572005, 'name': 'hotelF1 Roissy CDG', 'starRating': 1.0, 'urls': {},
       'address': {'streetAddress': '335 rue de la Belle Etoile', 'extendedAddress': 'ZAC Paris Nord 2',
                   'locality': 'Roissy-en-France', 'postalCode': '95974', 'region': '', 'countryName': 'France',
                   'countryCode': 'fr', 'obfuscate': False},
       'landmarks': [{'label': 'City center', 'distance': '12 miles'},
                     {'label': 'Eiffel Tower', 'distance': '13 miles'}],
       'ratePlan': {'price': {'current': '$30', 'exactCurrent': 30.13}}},
      {'id': 579223, 'name': 'hotelF1 Paris Saint-Denis Université',
       'address': {'streetAddress': '11 avenue Lenine', 'extendedAddress': '', 'locality': 'Saint-Denis',
                   'postalCode': '93200', 'region': '', 'countryName': 'France', 'countryCode': 'fr',
                   'obfuscate': False},
       'landmarks': [{'label': 'City center', 'distance': '5.3 miles'},
                     {'label': 'Eiffel Tower', 'distance': '6.5 miles'}],
       'geoBullets': [], 'ratePlan': {'price': {'current': '$33', 'exactCurrent': 33.14}}},
      {'id': 2343790400, 'name': 'easyHotel Paris Charles de Gaulle',
       'address': {'streetAddress': '10 Rue de la Belle Borne', 'extendedAddress': '', 'locality': 'Tremblay-en-France',
                   'postalCode': '93290', 'region': 'Roissy', 'countryName': 'France', 'countryCode': 'fr',
                   'obfuscate': False},
       'landmarks': [{'label': 'City center', 'distance': '12 miles'},
                     {'label': 'Eiffel Tower', 'distance': '14 miles'}],
       'geoBullets': [], 'ratePlan': {'price': {'current': '$34', 'exactCurrent': 33.77}}}]]
]
